#!/bin/sh
# read smiles file

#echo "Enter the input file name"
#read file
file='inp.smi'
c=`expr length $file`
d=`expr $c - 4`
s=`echo $file |cut -c 1-$d`
./smi2sdf -o rough.sdf $s.smi                  # Command to generate the rough coodinates from
                                                                   # SMILES string.
./mengine -p mmff94.prm  -c mmxconst.prm -o out.sdf rough.sdf # Command to generate the 3D coordinates.

babel -isdf out.sdf -omol2 out.mol2 3>&-                    # File format conversion.
cp out.mol2 tem.mol2
perl findrotatable.pl out.mol2                                # Command to find the rotatable bonds.
perl lsrot.pl out.sdf out.aux out.rot                         # Command to list the number of neighbouring
                                                              # atoms that gets rotated.
cc sam.c                                                      # Command to sort and list the atoms.
./a.out out.rot out.out

mv out.mol2 lout.mol2

#./o4 -i out.mol2 -e 2>&-                                      # Command to calculate the energy of the
##sh bab_ene.sh                                                              # molecule.
##cat ene1.txt
##rm ene1.txt
#mv energy.txt out.ene
#grep "Tot_Energy" energy.txt
##rm *_inorg.smi*                                               #Deleting the unwanted files.
#rm out.0000.ffa
#rm out.0000.mol2
#rm out.0000.pdb
##rm error.log 

